name: distmetrics
dependencies:
 - python>=3.10
 - pip
 - scikit-image
 - numpy
 - scipy
 - matplotlib
 - rasterio
 - astropy
 - gdal
 - pydantic
 - astropy
 - jupyterlab
 - tqdm
 - shapely
 - requests
 - backoff
 - asf_search
 - mpire
 - multiprocess
 - dill
 - geopandas
 - pandas
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - pytest
 - pytest-cov
 - ruff