name: distmetrics
dependencies:
 - python>=3.12
 - asf_search
 - astropy
 - backoff
 - compilers
 - dem_stitcher
 - einops
 - flake8
 - flake8-blind-except
 - flake8-builtins
 - flake8-import-order
 - gdal
 - geopandas
 - jupyterlab
 - matplotlib
 - numpy
 - pandas
 - pydantic
 - pytest
 - pytest-cov
 - pytorch>=*=cuda118*
 - rasterio>=1.4.3
 - requests
 - ruff
 - scikit-image
 - scipy
 - setuptools
 - setuptools_scm
 - shapely
 - tqdm
 - pip
#  - pip:
#    - torchvision 
#    - torchaudio
#    - torch-tensorrt
#    - nvidia-modelopt[all]